name: Build Pillow Layer

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Pillow layer (using AWS SAM build image)
        run: |
          docker run --rm -v "$PWD":/var/task public.ecr.aws/sam/build-python3.12:latest /bin/bash -lc "python -m pip install --upgrade pip && pip install -r requirements.txt -t python --upgrade && chmod -R a+r python"
          zip -r pillow_layer_py3.12.zip python

      - name: Upload layer zip
        uses: actions/upload-artifact@v4
        with:
          name: pillow_layer_py3.12.zip
          path: pillow_layer_py3.12.zip